development:
  adapter: postgresql
  encoding: utf8
  database: sqwat_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sqwat_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: sqwat_production
  pool: 5
  username:
  password:
